language: python
python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
env:
  # Python 3 versions for Tox
  - TOX_ENV=py38
  - TOX_ENV=py39
  - TOX_ENV=py310
  - TOX_ENV=py311
  - TOX_ENV=py312
  - TOX_ENV=lint
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y clamav-daemon clamav-freshclam
  - sudo freshclam --verbose
  - sudo service clamav-daemon start
  - pip install tox
script: tox -e $TOX_ENV
